# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Array": "00_data.ipynb",
         "Shape": "00_data.ipynb",
         "CircArrayBuffer": "00_data.ipynb",
         "CameraProperties": "00_data.ipynb",
         "CameraProperties.tfm_setup": "00_data.ipynb",
         "CameraProperties.crop": "00_data.ipynb",
         "CameraProperties.fast_smile": "00_data.ipynb",
         "CameraProperties.fast_bin": "00_data.ipynb",
         "CameraProperties.pipeline": "00_data.ipynb",
         "DataCube": "00_data.ipynb",
         "Model6SV": "03_atmos.ipynb"}

modules = ["data.py",
           "camera.py",
           "calibrate.py",
           "atmos.py",
           "snr.py"]

doc_url = "https://openhsi.github.io/openhsi/"

git_url = "https://github.com/openhsi/openhsi/tree/master/"

def custom_doc_links(name): return None
