# AUTOGENERATED! DO NOT EDIT! File to edit: 07_atmosphere.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastcore.foundation import patch
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
import pandas as pd
import datetime

from ximea import xiapi
from tqdm import tqdm
import json
from typing import Iterable, Union