# AUTOGENERATED! DO NOT EDIT! File to edit: 02_calibrate.ipynb (unless otherwise specified).

__all__ = ['SettingsBuilderMixin', 'SettingsBuilderMetaclass', 'create_settings_builder']

# Cell

from fastcore.foundation import patch
from fastcore.meta import delegates
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.interpolate import interp1d
from PIL import Image
from scipy.signal import decimate

from typing import Iterable, Union, Callable, List, TypeVar, Generic, Tuple, Optional
import datetime
import json
import pickle

# Cell

from .data import *
from .capture import *

# Cell

class SettingsBuilderMixin():

    def say_hello(self,):
        print("Hello!")

# Cell

#export

class SettingsBuilderMetaclass(type):
    def __new__(cls, clsname:str, cam_class, attrs) -> "Class":
        """Create a SettingsBuilder class based on your chosen `CameraClass`."""
        return super(SettingsBuilderMetaclass, cls).__new__(cls, clsname, (cam_class,SettingsBuilderMixin), attrs)


def create_settings_builder(clsname:str, cam_class:"Camera Class") -> "SettingsBuilder Class":
    """Create a SettingsBuilder class based on your chosen `CameraClass`."""
    return type(clsname, (cam_class,SettingsBuilderMixin), {})

