# AUTOGENERATED! DO NOT EDIT! File to edit: 03_data.ipynb (unless otherwise specified).

__all__ = ['save']

# Cell

import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime



# Cell
import h5py
from netCDF4 import Dataset

# Cell
def save(data, fname:str = 'cal_files/fname', format:str = 'nc'):
    """Could move to the capture module as a class method instead"""
    with h5py.File(fname, "w") as f:
        dset = f.create_dataset("file")
        dset[...] = data