# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_geometry.ipynb (unless otherwise specified).

__all__ = []

# Cell

from fastcore.foundation import patch
from fastcore.meta import delegates
import numpy as np
import ctypes
import matplotlib.pyplot as plt
import warnings
from tqdm import tqdm
