# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/10_tutorial_calibrate.ipynb (unless otherwise specified).

__all__ = ['QUICK_START_GUIDE', 'GEN_CAL_FILES']

# Cell
QUICK_START_GUIDE = True

# Cell
GEN_CAL_FILES = True