# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tutorials/10_tutorial_calibrate.ipynb.

# %% auto 0
__all__ = ['GEN_CAL_FILES']

# %% ../nbs/tutorials/10_tutorial_calibrate.ipynb 2
GEN_CAL_FILES = True
