# AUTOGENERATED! DO NOT EDIT! File to edit: 04_visualise.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastcore.foundation import patch
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

import hvplot.xarray # noqa
import hvplot.pandas # noqa
import panel as pn
import panel.widgets as pnw
import ipywidgets as ipw