name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
    - name: Install the OpenHSI
      shell: bash -l {0}
      run: |
         pip install --upgrade pip setuptools wheel
         git clone https://github.com/YiweiMao/openhsi.git
         cd openhsi
         pip install -e .
    -  uses: openhsi/openhsi@yiweidev
#    - uses: fastai/workflows/quarto-ghp@master
#      with: {pre: 1} 