name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
#    - name: Install the OpenHSI
#      shell: bash -l {0}
#      run: |
#        git clone https://github.com/YiweiMao/openhsi.git
#        cd openhsi
#        pip install -e .
#    -  uses: fastai/workflows/quarto-ghp@master
    -  uses: YiweiMao/openhsi@main

